engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - angular-web-notification.js
exclude_paths:
  - test/**/*
  - test/*
  - example/**/*
  - example/*
  - docs/**/*
  - docs/*
  - Gruntfile.js
  - karma.conf.js
  - .editorconfig
  - .codeclimate.yml
  - LICENSE
  - *.json
  - **.json
  - *.md
  - **.md
  - *.yml
  - **.yml
  - *.*rc
  - **.*rc
