engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
ratings:
  paths:
    - angular-web-notification.js
exclude_paths:
  - test/**/*
  - test/*
  - example/**/*
  - example/*
  - docs/**/*
  - docs/*
  - Gruntfile.js
  - karma.conf.js
  - .editorconfig
  - .codeclimate.yml
  - LICENSE
  - README.md
  - bower.json
  - package.json
  - .*.json
  - .*.yml
  - .*rc
