engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - angular-web-notification.js
exclude_paths:
  - test/**/*
  - example/**/*
  - docs/**/*
  - Gruntfile.js
  - **/*.json
  - **/*.md
  - **/*.yml
  - .editorconfig
  - .jslintrc
  - LICENSE
